name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build Docker Image
        run: docker build . --file Dockerfile --tag bschrameck/arlo-cam-api:$(date +%s) --tag bschrameck/arlo-cam-api:latest
      - 
        name: Docker Push
        run: docker push --all-tags bschrameck/arlo-cam-api
